# VPBank K-MULT Agent Studio - Full Stack Deployment

services:
  # Backend Multi-Agent Service
  mutil-agent:
    build:
      context: ./src/backend
      dockerfile: app/mutil_agent/Dockerfile
    image: mutil-agent-backend
    container_name: vpbank-kmult-backend
    ports:
      - '8080:8080'
    env_file:
      - ./src/backend/app/mutil_agent/.env
    volumes:
      - ./logs/backend:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '-f',
          'http://localhost:8080/mutil_agent/public/api/v1/health-check/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - vpbank-kmult-network

  # Frontend React Application
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    image: mutil-agent-frontend
    container_name: vpbank-kmult-frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_ENV=production
    volumes:
      - ./logs/frontend:/app/logs
    restart: unless-stopped
    depends_on:
      - mutil-agent
    networks:
      - vpbank-kmult-network

networks:
  vpbank-kmult-network:
    external: true

volumes:
  backend-logs:
  frontend-logs:
  app-data:
