version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=github-${COMMIT_HASH:=latest}
      - echo Build started on `date`
      - echo Repository URI = $REPOSITORY_URI
      - echo Image tag = $IMAGE_TAG
      - echo Checking directory structure...
      - pwd
      - ls -la
      - echo Checking backend directory...
      - ls -la backend/
      - echo Checking for Dockerfile.prod...
      - ls -la backend/Dockerfile.prod
  
  build:
    commands:
      - echo Build phase started on `date`
      - echo Building the Docker image...
      - cd backend
      - echo Current directory after cd backend:
      - pwd
      - ls -la
      - echo Building Docker image with Dockerfile.prod...
      - docker build -f Dockerfile.prod -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
      - echo Docker build completed successfully
      
      # Optional: Run basic tests
      - echo Running basic container test...
      - docker run --rm $REPOSITORY_URI:latest python --version || echo "Python version check failed but continuing..."
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Docker images pushed successfully
      - echo Writing image definitions file...
      - printf '[{"name":"web","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
      - echo Build process completed successfully!

artifacts:
  files:
    - imagedefinitions.json
  name: VPBankKMultBuild-$(date +%Y-%m-%d)
